version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    command:
      - sh
      - -c
      - alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data